// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow for generating personalized manhwa recommendations.
 *
 * - generateManhwaRecommendations - A function that generates manhwa recommendations.
 * - ManhwaRecommendationsInput - The input type for the generateManhwaRecommendations function.
 * - ManhwaRecommendationsOutput - The return type for the generateManhwaRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ManhwaRecommendationsInputSchema = z.object({
  readingHistory: z
    .string()
    .describe('A list of manhwa titles the user has read.'),
  preferences: z
    .string()
    .describe('The user preferences (genres, authors, etc.)'),
});
export type ManhwaRecommendationsInput = z.infer<
  typeof ManhwaRecommendationsInputSchema
>;

const ManhwaRecommendationsOutputSchema = z.object({
  recommendations: z
    .string()
    .describe('A list of recommended manhwa titles based on reading history and preferences.'),
});
export type ManhwaRecommendationsOutput = z.infer<
  typeof ManhwaRecommendationsOutputSchema
>;

export async function generateManhwaRecommendations(
  input: ManhwaRecommendationsInput
): Promise<ManhwaRecommendationsOutput> {
  return generateManhwaRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'manhwaRecommendationsPrompt',
  input: {schema: ManhwaRecommendationsInputSchema},
  output: {schema: ManhwaRecommendationsOutputSchema},
  prompt: `You are a manhwa recommendation expert. Based on the user's reading history and preferences, you will provide personalized manhwa recommendations.

Reading History: {{{readingHistory}}}
Preferences: {{{preferences}}}

Recommendations:`,
});

const generateManhwaRecommendationsFlow = ai.defineFlow(
  {
    name: 'generateManhwaRecommendationsFlow',
    inputSchema: ManhwaRecommendationsInputSchema,
    outputSchema: ManhwaRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
